export const APP_VERSION = "1.0.0";

export const CHAPTERS = [
  {
    id: "harbor-launch",
    title: "Harbor Launch",
    theme: "cozy-launch",
    sceneState: "idle-cruise",
    briefing:
      "Warm up the crew. Captain restores the launch checklist while Engineer settles the cockpit systems.",
    captainDirective: "Recover the launch phrase and guide the first route callout.",
    engineerDirective: "Calm the cockpit by restoring order to the opening maintenance puzzle.",
    resolutionTitle: "Harbor Crew Harmony",
    resolutionBody:
      "The launch went smoothly. The crew trusts the shared routine: clue, response, confirm, commit.",
    rewardTreasure: 10,
    routes: ["treasure-waters", "storm-repair"],
    routeLabel: "Choose the first true voyage lane together.",
    timerMs: 150000,
    difficulty: 1,
    challengeType: "launch-sequence",
  },
  {
    id: "treasure-waters",
    title: "Treasure Waters",
    theme: "treasure-map",
    sceneState: "treasure-sighting",
    briefing:
      "A glittering island rises on the horizon. The Captain reads the clue while the Engineer works the grid.",
    captainDirective: "Decode the map phrase and call out the safe treasure path.",
    engineerDirective: "Keep the route tools clear and act on the Captain's clue.",
    resolutionTitle: "Treasure Signal Captured",
    resolutionBody:
      "The crew turns shared clues into action. Treasure is earned by careful listening, not by guessing fast.",
    rewardTreasure: 22,
    routes: ["pirate-intercept", "storm-repair"],
    routeLabel: "Commit to a richer route or take the safer weather lane.",
    timerMs: 165000,
    difficulty: 2,
    challengeType: "treasure-grid",
  },
  {
    id: "pirate-intercept",
    title: "Pirate Intercept",
    theme: "pirate-warning",
    sceneState: "pirate-approach",
    briefing:
      "A toy pirate crew drifts into view. Stay playful but sharp: Captain relays warnings while Engineer stabilizes defenses.",
    captainDirective: "Relay the defense signal before pirate pressure spikes.",
    engineerDirective: "Sort and route the defense systems while listening for the pirate callout.",
    resolutionTitle: "Playful Defense Drill",
    resolutionBody:
      "The pirate chapter proves the loop: one player reads intent, the other executes, then both confirm the next move.",
    rewardTreasure: 18,
    routes: ["storm-repair", "harbor-launch"],
    routeLabel: "Patch up now or loop back for a calmer supply run.",
    timerMs: 170000,
    difficulty: 3,
    challengeType: "pirate-defense",
  },
  {
    id: "storm-repair",
    title: "Storm Repair",
    theme: "storm-emergency",
    sceneState: "storm-emergency",
    briefing:
      "The sea turns rough. Captain keeps the route readable while Engineer reorders a cockpit under pressure.",
    captainDirective: "Recover the warning code and make the crew's route choice readable again.",
    engineerDirective: "Repair fast, then confirm the safe lane with the Captain.",
    resolutionTitle: "Storm Confidence",
    resolutionBody:
      "A soft failure is still a lesson. The boat bends, the crew adapts, and the voyage continues.",
    rewardTreasure: 14,
    routes: ["treasure-waters", "pirate-intercept"],
    routeLabel: "Take the recovered route and continue the voyage.",
    timerMs: 150000,
    difficulty: 2,
    challengeType: "storm-recovery",
  },
];

export const CHAPTER_LOOKUP = Object.fromEntries(CHAPTERS.map((chapter) => [chapter.id, chapter]));

export const VOYAGE_SCENES = {
  "idle-cruise": {
    id: "idle-cruise",
    title: "Idle Cruise",
    subtitle: "The crew glides into open water and checks every station before committing to the route.",
    mood: "clear-sky",
    callout: "Start with communication, not speed.",
  },
  "treasure-sighting": {
    id: "treasure-sighting",
    title: "Treasure Sighting",
    subtitle: "The island and its treasure clue appear together. One player reads; one player confirms.",
    mood: "gold-haze",
    callout: "Say the clue slowly and verify the grid before acting.",
  },
  "pirate-approach": {
    id: "pirate-approach",
    title: "Pirate Approach",
    subtitle: "Pirate toys drift into range. Keep the tone playful and the callouts exact.",
    mood: "warning-red",
    callout: "Defense works best when both roles repeat the plan.",
  },
  "storm-emergency": {
    id: "storm-emergency",
    title: "Storm Emergency",
    subtitle: "The cockpit shakes. Repair first, confirm second, and keep the route readable.",
    mood: "storm-blue",
    callout: "Soft failure is okay. Recover, confirm, continue.",
  },
};

export const TREASURE_ROUNDS = [
  {
    id: "berry-cove",
    title: "Berry Cove Cache",
    target: "B4",
    hazards: ["C3", "D2"],
    clue: "From the palm tree, sail two squares east, then one square south. Stop before the reef marker.",
    mapNote: "Palm tree starts at A3. Reef warning: C3. Whirlpool warning: D2.",
    reward: "A berry-stamped key and 18 gold coins slide into the toy treasure locker.",
  },
  {
    id: "pearl-bank",
    title: "Pearl Bank Marker",
    target: "D2",
    hazards: ["B2", "E4"],
    clue: "Find the pearl bank on row 2. Count four columns from the left edge and confirm the shark shadow first.",
    mapNote: "Pearl bank crosses row 2. Shark shadow at B2. Storm pocket at E4.",
    reward: "A pearl compass lens unlocks another owner's manual chapter.",
  },
  {
    id: "skull-sandbar",
    title: "Skull Sandbar Detour",
    target: "C5",
    hazards: ["C4", "A5"],
    clue: "Follow the bottom current to row 5. The safe X is centered on the map, just below the skull sandbar.",
    mapNote: "Safe row: 5. Center column: C. Skull sandbar at C4. Jagged rocks at A5.",
    reward: "A glossy ruby anchor charm is added to the boat shelf.",
  },
];

export const COSMETIC_UNLOCKS = [
  { manualPage: 0, category: "steeringWheels", id: "wheel-classic", name: "Classic Toy Wheel" },
  { manualPage: 0, category: "seats", id: "seat-navy", name: "Navy Captain Chair" },
  { manualPage: 0, category: "players", id: "player-kyle", name: "Player Kyle" },
  { manualPage: 0, category: "players", id: "player-rochelle", name: "Player Rochelle" },
  { manualPage: 0, category: "boats", id: "boat-pirate-brown", name: "Brown Pirate Ship" },
  { manualPage: 0, category: "environments", id: "env-boat-cockpit", name: "Boat Cockpit Environment" },
  { manualPage: 1, category: "steeringWheels", id: "wheel-brass", name: "Royal Brass Wheel" },
  { manualPage: 2, category: "seats", id: "seat-cream", name: "Cloud Cream Chair" },
  { manualPage: 3, category: "steeringWheels", id: "wheel-pirate", name: "Pirate Bone Wheel" },
  { manualPage: 3, category: "pirates", id: "pirate-one", name: "Pirate Mate One" },
  { manualPage: 4, category: "seats", id: "seat-pirate", name: "Pirate Red Chair" },
  { manualPage: 5, category: "players", id: "player-vickie", name: "Player Vickie" },
  { manualPage: 6, category: "islands", id: "island-castleberry-cove", name: "Castleberry Cove Island" },
];

export const SWITCHES = [
  "nav",
  "radio",
  "pump",
  "fuel",
  "lights",
  "gps",
  "manual",
  "defense",
  "aux-a",
  "aux-b",
  "aux-c",
  "aux-d",
].map((id, index) => ({ id, name: "", on: index % 3 !== 0, alert: index < 8 }));

export const CAPTAIN_TASKS = [
  {
    id: "radio-check",
    role: "captain",
    type: "word-search",
    title: "Decode Radio Call",
    target: "RADIO",
    hint: "Tap R-A-D-I-O in order, then call the word out loud.",
    step: "Restore the comms word before the route fades.",
  },
  {
    id: "signal-flag",
    role: "captain",
    type: "word-search",
    title: "Signal Flag Scan",
    target: "ANCHOR",
    hint: "Trace A-N-C-H-O-R to recover the safe harbor signal.",
    step: "Read the target word, then tap each letter in order.",
  },
  {
    id: "plot-course",
    role: "captain",
    type: "letter-bank",
    title: "Build Navigation Term",
    target: "COMPASS",
    letters: "ASCOMPS",
    hint: "Use all letters to build the missing manual heading.",
    step: "Assemble the heading and confirm it with your partner.",
  },
  {
    id: "storm-phrase",
    role: "captain",
    type: "letter-bank",
    title: "Repair Radio Phrase",
    target: "MAYDAY",
    letters: "YDAMAY",
    hint: "Assemble the emergency radio call.",
    step: "Build the phrase and tell the engineer the warning is clear.",
  },
  {
    id: "treasure-term",
    role: "captain",
    type: "letter-bank",
    title: "Treasure Clue Phrase",
    target: "BERRY",
    letters: "RYEBR",
    hint: "Build the hidden clue word and say it slowly.",
    step: "Assemble the clue word to add it to the owner's manual.",
  },
  {
    id: "semaphore-relay",
    role: "captain",
    type: "signal-relay",
    title: "Semaphore Relay",
    targetSignals: ["wave", "flag", "bell", "star"],
    hint: "Repeat the signal order exactly so your partner can follow the lane.",
    step: "Read the signal order and confirm each icon in sequence.",
  },
  {
    id: "pirate-warning",
    role: "captain",
    type: "code-select",
    title: "Pirate Warning Phrase",
    prompt: "Which playful warning keeps the crew calm and precise?",
    options: ["RED SAIL", "HOLD FAST", "BONE BELL", "WAVE BRACE"],
    answer: "HOLD FAST",
    hint: "Pick the phrase that sounds like a calm defense callout.",
    step: "Choose the best pirate warning and speak it to the crew.",
  },
];

export const ENGINEER_TASKS = [
  {
    id: "coolant-sort",
    role: "engineer",
    type: "liquid-sort",
    title: "Balance Coolant Tubes",
    hint: "Move matching liquid colors into clean tubes.",
    step: "Tap a tube to pick up the top liquid, then tap a valid tube to pour it.",
  },
  {
    id: "wire-route",
    role: "engineer",
    type: "connect-dots",
    title: "Reconnect Circuit",
    hint: "Tap dots 1 through 5 to restore the maintenance circuit.",
    step: "Follow the numbered route without skipping a dot.",
  },
  {
    id: "part-match",
    role: "engineer",
    type: "matching",
    title: "Match Spare Parts",
    hint: "Find all matching boat system icons.",
    step: "Flip two cards at a time and pair every icon.",
  },
  {
    id: "fuel-sort",
    role: "engineer",
    type: "liquid-sort",
    title: "Separate Fuel Additives",
    hint: "Sort the fluids before the engine clogs.",
    step: "Use the empty tube as your workspace.",
  },
  {
    id: "valve-route",
    role: "engineer",
    type: "connect-dots",
    title: "Trace Bilge Valve Path",
    hint: "Tap each numbered valve in order.",
    step: "The circuit glows as you trace the correct route.",
  },
  {
    id: "breaker-balance",
    role: "engineer",
    type: "breaker-balance",
    title: "Balance Breaker Panel",
    targetSwitches: ["nav", "fuel", "gps", "defense"],
    hint: "Activate the target breakers and leave the others resting.",
    step: "Read the target row and settle the right switches.",
  },
  {
    id: "cargo-sort",
    role: "engineer",
    type: "cargo-sort",
    title: "Cargo Grouping",
    targetGroups: { fruit: 3, tools: 3, treasure: 3 },
    hint: "Drag cargo into the matching hold lane by category.",
    step: "Group the crates before the boat lists.",
  },
  {
    id: "pulse-sequence",
    role: "engineer",
    type: "sequence-repeat",
    title: "Power Pulse Repeat",
    sequence: ["amber", "blue", "amber", "green"],
    hint: "Repeat the pulse lights in the same order.",
    step: "Watch once, then repeat the sequence cleanly.",
  },
];

export const INTERLUDES = {
  "treasure-waters": {
    type: "waypoint",
    sceneState: "treasure-sighting",
    title: "Chart the Treasure Lane",
    subtitle: "Captain reads the chart marker. Engineer confirms the shared waypoint before the island comes into focus.",
    prompt: "Call out the safe grid marker and confirm the same waypoint together.",
    captainDirective: "Read the grid clue and pick the waypoint that opens the treasure lane.",
    engineerDirective: "Listen for the Captain's callout and confirm the same waypoint on the route panel.",
    options: [
      { id: "A3", label: "A3", note: "Palm marker" },
      { id: "B4", label: "B4", note: "Safe berry channel" },
      { id: "C3", label: "C3", note: "Reef shadow" },
      { id: "D2", label: "D2", note: "Whirlpool edge" },
    ],
    target: "B4",
  },
  "storm-repair": {
    type: "storm",
    sceneState: "storm-emergency",
    title: "Storm Recovery Choice",
    subtitle: "Dark water pushes in. Recover the safest response before the next chapter begins.",
    prompt: "Pick the same storm response together. The wrong call costs hull and morale.",
    captainDirective: "Read the weather tone and choose the safest recovery callout.",
    engineerDirective: "Match the Captain's storm response and confirm the repair posture.",
    options: [
      { id: "batten-down", label: "Batten Down", note: "Secure and stabilize first." },
      { id: "full-speed", label: "Full Speed", note: "Push through the front fast." },
      { id: "lights-out", label: "Lights Out", note: "Hide and drift silently." },
    ],
    target: "batten-down",
  },
  "pirate-intercept": {
    type: "hazard",
    sceneState: "pirate-approach",
    title: "Pirate Signal Callout",
    subtitle: "A pirate silhouette crosses the lane. Captain and Engineer must match the same calm signal.",
    prompt: "Repeat the same pirate response together to keep pressure low.",
    captainDirective: "Choose the pirate warning that keeps the crew precise instead of frantic.",
    engineerDirective: "Mirror the Captain's callout so the defense lane stays coordinated.",
    options: [
      { id: "hold-fast", label: "Hold Fast", note: "Stay calm and coordinate." },
      { id: "ring-bell", label: "Ring Bell", note: "Loud warning, scattered response." },
      { id: "cut-east", label: "Cut East", note: "Sharp evasive move." },
    ],
    target: "hold-fast",
  },
  "harbor-launch": {
    type: "port",
    sceneState: "idle-cruise",
    title: "Harbor Resupply Stop",
    subtitle: "Before looping back, the crew agrees on which harbor node gives the calmest reset.",
    prompt: "Captain chooses a port node, then Engineer confirms the same stop.",
    captainDirective: "Pick the harbor that best resets morale and route clarity.",
    engineerDirective: "Confirm the same harbor node after the Captain calls it out.",
    options: [
      { id: "port-royal", label: "Port Royal", note: "Well-lit calm harbor" },
      { id: "tortuga", label: "Tortuga", note: "Lively but distracting" },
      { id: "nassau", label: "Nassau", note: "Busy trade lane" },
    ],
    target: "port-royal",
  },
};
